attrs:
  board_add_column_cmd:
    module_path: app.commands.board
    class_name: AddColumn
  board_list_columns_cmd:
    module_path: app.commands.board
    class_name: ListColumns
  board_delete_column_cmd:
    module_path: app.commands.board
    class_name: DeleteColumn
  item_update_simple_column_value_cmd:
    module_path: app.commands.item
    class_name: UpdateSimpleColumnValue
  get_moncli_item_cmd:
    module_path: app.commands.moncli
    class_name: GetMoncliItem
  board_repo:
    module_path: app.proxies.moncli.board
    class_name: BoardMoncliProxy
  item_repo:
    module_path: app.proxies.moncli.item
    class_name: ItemMoncliProxy

const: 
  monday_api_key: $env.TIFERET_MONDAY_API_KEY