interfaces:
  tiferet_monday:
    name: Tiferet Monday
    description: An interface for Tiferet Monday
    attrs:
      features:
        module_path: tiferet_monday.contexts.feature
        class_name: MondayFeatureContext
    const:
      feature_config_file: tiferet_monday/configs/feature.yml
      container_config_file: tiferet_monday/configs/container.yml
      error_config_file: tiferet_monday/configs/error.yml
      logging_config_file: tiferet_monday/configs/logging.yml