logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      name: Simple Formatter
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    file:
      name: File Handler
      module_path: logging
      class_name: FileHandler
      formatter: simple
      level: INFO
      filename: tiferet_monday.log
    console:
      name: Console Handler
      module_path: logging
      class_name: StreamHandler
      formatter: simple
      level: WARNING
      stream: ext://sys.stdout
  loggers:
    tiferet_monday:
      name: Tiferet Monday Logger
      level: INFO
      handlers: [file]
      propagate: no
    root:
      name: Root Logger
      level: WARNING
      handlers: [console]
      is_root: true